import { useEffect,useState } from 'react';
import { button,primary,input,Page,Card,Field,Notice,useData,useAction } from '../ui';
import { ExcludedItems,LibrarySpace } from '../LibraryTools';
import { managementApi } from './Sources';
export { ModelSettings } from './ModelSettings';

export function ProcessingSettings({api}) {
  const query=useData(api,'/v1/management/overview'),preferences=useData(api,'/v1/management/preferences'),action=useAction();const [enabled,setEnabled]=useState(false),[calls,setCalls]=useState(50),[tasks,setTasks]=useState(5),[download,setDownload]=useState(true),[maxDownload,setMaxDownload]=useState(1024);
  useEffect(()=>{if(query.data){setEnabled(query.data.automatic.enabled);setCalls(query.data.automatic.max_calls_per_task??50);setTasks(query.data.automatic.max_new_tasks||5)}},[query.data]);
  useEffect(()=>{if(preferences.data){setDownload(preferences.data.download_media);setMaxDownload(preferences.data.max_download_mb??1024)}},[preferences.data]);
  return <Page title="处理设置"><Notice error>{query.error||preferences.error||action.error}</Notice><Notice>{action.notice}</Notice>
    <Card title="原始媒体"><label className="flex items-center justify-between text-sm"><span>默认保存原视频 / 图片</span><input type="checkbox" checked={download} onChange={event=>setDownload(event.target.checked)}/></label><Field label="单个文件最大下载大小（MB）"><input className={input} type="number" inputMode="numeric" min={1} max={preferences.data?.max_download_mb_allowed??2048} step={1} value={maxDownload} onChange={event=>setMaxDownload(event.target.value)}/></Field><p className="text-sm text-zinc-500">可设 1–{preferences.data?.max_download_mb_allowed??2048} MB，默认 1024 MB。用于后续下载；不删除已有文件，也不改变模型上传限制。</p></Card>
    <Card title="新内容自动提取"><label className="flex items-center justify-between text-sm"><span>自动提取新保存的内容</span><input type="checkbox" checked={enabled} onChange={event=>setEnabled(event.target.checked)}/></label><p className="text-sm text-zinc-500">仅处理启用之后的新内容。历史资料可在任务页手动提取。</p>
      {enabled&&<><Field label="本次最多自动提取"><select className={input} value={tasks} onChange={event=>setTasks(Number(event.target.value))}>{[5,10,20].map(n=><option key={n} value={n}>{n} 条</option>)}</select></Field><details className="text-sm text-zinc-500"><summary className="cursor-pointer">高级设置</summary><div className="mt-3"><Field label="单条最多模型请求"><input className={input} type="number" min={1} max={1000} value={calls} onChange={event=>setCalls(Number(event.target.value))}/></Field></div></details></>}
      {query.data?.automatic.enabled&&<p className="text-sm text-zinc-500">本次还可自动提取 {query.data.automatic.remaining_new_tasks} 条</p>}
    </Card>
    <div className="flex justify-end gap-3"><button className={button} disabled={action.busy} onClick={()=>{setEnabled(false);setDownload(true);setMaxDownload(1024);setCalls(50);setTasks(5);action.setNotice('已恢复默认选项，点击保存后生效。')}}>恢复默认</button><button className={primary} disabled={action.busy||query.busy||preferences.busy} onClick={()=>action.run(async()=>{const maximum=Number(maxDownload);if(!Number.isInteger(maximum)||maximum<1||maximum>(preferences.data?.max_download_mb_allowed??2048))throw new Error('请填写有效的最大下载大小。');if(enabled&&!confirm(`开启自动提取？最多 ${tasks} 条，每条最多 ${calls} 次模型请求，会上传音频和所选画面；费用取决于你的服务。`))return;await managementApi(api,'preferences-save',{download_media:download,max_download_mb:maximum});await managementApi(api,'automatic',{enabled,max_calls:enabled?Number(calls):0,max_new_tasks:Number(tasks),fee_confirmed:enabled});query.refresh();preferences.refresh();action.setNotice('处理设置已保存。')})}>保存设置</button></div>
  </Page>;
}

export function StorageSettings({api,download,density,onDensity}) {
  const usage=useData(api,'/v1/management/overview'),preferences=useData(api,'/v1/management/preferences'),action=useAction();const [more,setMore]=useState([]),[next,setNext]=useState(null);
  useEffect(()=>{if(!more.length)setNext(usage.data?.next_offset??null)},[usage.data]);
  const jobs=[...(usage.data?.jobs||[]),...more.filter(row=>!usage.data?.jobs.some(job=>job.job_id===row.job_id))];
  return <Page title="数据与存储"><LibrarySpace api={api} initiallyOpen/><Card title="资料目录"><Notice error>{preferences.error}</Notice><p className="break-all text-sm text-zinc-500">{preferences.data?.workspace_path||'读取中…'}</p><button className={button} disabled={!preferences.data} onClick={()=>action.run(async()=>{await navigator.clipboard.writeText(preferences.data.workspace_path);action.setNotice('目录路径已复制。')})}>复制目录路径</button><Notice>{action.notice}</Notice></Card>{onDensity&&<Card title="显示"><Field label="界面密度"><select className={input} value={density} onChange={event=>onDensity(event.target.value)}><option value="compact">紧凑</option><option value="standard">标准</option><option value="relaxed">宽松</option></select></Field></Card>}<Card title="已隐藏资料"><ExcludedItems api={api} download={download} onChanged={usage.refresh}/></Card><Card title="模型用量"><Notice error>{usage.error||action.error}</Notice>{usage.data&&<><p className="text-sm text-zinc-500">用量随任务记录。未提供价格的费用显示未知。</p>{jobs.filter(job=>job.recorded_calls>0).map(job=><details key={job.job_id} className="rounded-xl bg-zinc-50 p-3 text-sm"><summary className="cursor-pointer">{job.title} · {job.recorded_calls} 次请求 · 费用未知</summary><div className="mt-3 space-y-3">{job.calls.map((call,index)=><div key={index} className="flex flex-wrap justify-between gap-2 border-t border-zinc-200 pt-2"><span>{call.model||'模型未返回'} · {call.state==='completed'?'已完成':call.state==='unknown'?'结果不明':'已发起'}</span><span className="text-zinc-500">输入 {call.usage?.prompt_tokens??call.usage?.input_tokens??'未知'} · 输出 {call.usage?.completion_tokens??call.usage?.output_tokens??'未知'} · 缓存 {call.usage?.cached_tokens??call.usage?.prompt_tokens_details?.cached_tokens??call.usage?.cache_read_input_tokens??'未知'}</span></div>)}</div></details>)}{!jobs.some(job=>job.recorded_calls>0)&&<p className="text-sm text-zinc-500">已加载任务中没有模型调用记录。</p>}{next!=null&&<button className={button} disabled={action.busy} onClick={()=>action.run(async()=>{const data=await managementApi(api,'overview',{offset:next});setMore(old=>[...old,...data.jobs]);setNext(data.next_offset)})}>加载更多记录</button>}</>}</Card></Page>;
}
